input.onButtonPressed(Button.A, function () {
    for (let index = 0; index < 4; index++) {
        basic.showIcon(IconNames.Heart)
        basic.pause(500)
        basic.clearScreen()
        basic.pause(500)
        basic.showString("Hello!")
        basic.clearScreen()
        basic.pause(500)
        basic.showArrow(ArrowNames.North)
        basic.pause(500)
        basic.clearScreen()
    }
})
input.onButtonPressed(Button.B, function () {
    led.plot(0, 2)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
    led.plot(2, 0)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
    led.plot(2, 4)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
    led.plot(4, 2)
    basic.pause(500)
    basic.clearScreen()
    basic.pause(500)
})
